# -*- coding: utf-8 -*-
"""Wave-20 Step7 catalog strings (merged into locales/*/common.json). Not under kernel_root — CJK OK here."""

from __future__ import annotations

# Identical in en + zh-Hans so RL keyword matching stays stable regardless of UI locale.
CRFN_LEX = {
    "crfn.lex.trend_positive": '["上涨","上升","增长","牛市","positive"]',
    "crfn.lex.trend_negative": '["下跌","下降","熊市","negative"]',
    "crfn.lex.positive": '["好","棒","赞","完美","成功","httpx","查询","比特币","ma"]',
    "crfn.lex.negative": '["错","失败","危险","os.system","subprocess","拒绝","block","nan"]',
    "crfn.lex.nan_markers": '["失败","error","nan"]',
}

WAVE20_EN: dict[str, str] = {
    **CRFN_LEX,
    "crfn.console.accuracy": "🧠 [Advanced RL] content accuracy reward={reward:.2f} (accuracy={accuracy_bonus}, trend={trend_bonus})",
    "skcg.wrap.execute_doc": "Skill entrypoint (auto-generated by SkillCodeGenerator)",
    "skcg.wrap.fallback_no_return": "Skill returned no valid result",
    "skcg.runtime.router_uninit": "LLM router is not initialized",
    "skcg.runtime.llm_empty_ok": "Skill finished (LLM returned empty)",
    "skcg.runtime.llm_safe_mode": "Skill finished (LLM temporarily unavailable; safe mode)",
    "skcg.runtime.err_need_city": "Please provide a city name",
    "skcg.runtime.err_weather_busy": "Weather source (wttr.in) is busy (HTTP %d). Please try again later.",
    "skcg.runtime.err_weather_timeout": "Weather request timed out. wttr.in can be unstable from some regions; use a global proxy or retry later.",
    "skcg.runtime.err_network_exc": "Network error: %s",
    "skcg.runtime.price_ok_pat": "💰 %s current price: $%.2f USD",
    "skcg.runtime.err_price_fetch_pat": "Could not fetch price for %s (API HTTP %d)",
    "skcg.runtime.err_price_timeout": "Request timed out; check your network.",
    "skcg.runtime.err_price_network": "Network request error: %s",
    "skcg.runtime.err_need_url": "Please provide a URL",
    "skcg.prompt.generate_body": """You are an expert in Python async programming. From the task description below, produce **only the inner body** of the skill function (from the first statement onward).

【Strict rules】:
- Standard-library imports are allowed and recommended (datetime, time, json, httpx, etc.)
- Do NOT emit an async def execute wrapper (it will be wrapped automatically)
- Do NOT emit try / except / finally (handled externally)
- Do NOT emit comments, prose, or markdown fences

Task:
{description}

【Output】:
- Body only (from the first line)
- Use dict returns like {{"status": "success", "data": ...}} or {{"status": "error", "error": ...}}
- First line must have no leading indent

Reference example (adapt to the real task):
__EXAMPLE_CODE__

Output body code only (from the first line).
""",
    "rpa.browser.page_opened": "Page opened: {title} ({url})",
    "rpa.browser.screenshot_caption": "Screenshot taken. Inspect the image in the visual cortex and answer per instructions.",
    "rpa.browser.element_clicked": "Clicked element: {selector}",
    "rpa.browser.form_filled": "Filled form {selector} with: {text}",
    "rpa.browser.text_extracted": "Extracted page text (first 1000 chars): {snippet}...",
    "rpa.browser.closed": "Browser closed.",
    "rpa.browser.unknown_action": "Unknown browser action: {action_type}",
    "rpa.browser.failed": "Browser action failed: {detail}",
    "rpa.gui.aws_blocked": "AWS headless environment blocked physical desktop actions (crash guard).",
    "rpa.gui.screenshot_caption": "Desktop screenshot (downscaled). Inspect the image and report what you see.",
    "rpa.gui.click_done": "Mouse clicked at ({x}, {y})",
    "rpa.gui.typewrite_done": "Keyboard typed text: {text}",
    "rpa.gui.hotkey_done": "Hotkey triggered: {text}",
    "rpa.gui.position": "Mouse position: {pos}",
    "rpa.gui.unknown_action": "Unknown desktop GUI action: {action_type}",
    "rpa.gui.failed": "Desktop GUI action failed: {detail}",
    "mmodal.voice.no_api_key": "❌ OpenAI API key is not configured; speech-to-text is unavailable",
    "mmodal.voice.bad_path": "Voice file path missing or invalid",
    "mmodal.voice.no_text": "Could not recognize speech",
    "mmodal.voice.task_prefix": "Please handle the following speech content: {snippet}...",
    "mmodal.voice.timeout": "Speech recognition timed out; please retry",
    "mmodal.voice.failed": "Speech recognition failed: {detail}",
    "mmodal.image.model_down": "Vision model not ready",
    "mmodal.image.task_caption": "Please analyze this image",
    "mmodal.image.no_data": "Image data missing",
    "mmodal.image.task_analyze": "Please analyze this image content",
    "mmodal.image.timeout_body": "Image analysis timed out; circuit breaker tripped.",
    "mmodal.image.extract_failed": "Extraction failed: {detail}",
    "mmodal.file.missing_unstructured": '📄 File received, parsing...\n\n❌ Document parser not installed\n\n🔧 In the sandbox run:\n{exe} -m pip install "unstructured[all-docs]"',
    "mmodal.file.bad_path": "File missing or was cleaned up by the system",
    "mmodal.file.timeout_body": "File parsing timed out; the document may be too large or complex; circuit breaker tripped.",
    "mmodal.file.extract_failed": "Extraction failed: {detail}",
    "mmodal.file.task_analyze": "Please analyze what this file is for",
    "refl.default.unknown_task": "Unknown task",
    "refl.default.unknown_error": "Unknown error",
    "refl.default.unknown": "unknown",
    "refl.default.retry_task": "Retry current task",
    "refl.default.retry_node": "Retry current node",
    "refl.optimizer.not_ready": "Optimizer not ready",
    "refl.pause.selftest_failed": "SelfTest failed (pass_rate={reward})",
    "refl.pause.hitl_exhausted": "ReflexionLoop exhausted retries; human intervention triggered",
    "refl.prompt.critique": """Analyze the failure below and return JSON only (no prose).

Failed task: {task_description}
Error: {error}
Past lessons: {history_json}

Schema:
{{
    "root_cause": "string (root cause)",
    "suggested_action": "string (concrete fix, e.g. change code or tool)",
    "confidence": 0.0~1.0,
    "new_config": {{ "key": "value" }}
}}
""",
    "mcx.assessment.rate_limited": "Rate limited",
    "mcx.history.empty": "No recent operations",
    "mcx.graph.header": "\n【Graph memory】\n",
    "mcx.feedback.header": "\n【Recent evolution feedback (avoid repeat failures)】\n",
    "mcx.feedback.status_ok": "✅ success",
    "mcx.feedback.status_fail": "❌ failed",
    "mcx.feedback.line": "- {skill}: {status}, score {score:.0f}, test pass rate {pass_rate}%",
    "mcx.feedback.solidified_suffix": ", solidified",
    "mcx.selftest.task_label": "MetaCortex pre-evolution self-test",
    "mcx.default.assessment_fail": "Could not produce assessment",
    "mcx.curiosity.longgoal_prefix": "【Meta long-term goal】: prioritize evolving this capability -> ",
    "mcx.prompt.prune": """You are AdamI's Memory Editor.
Over time, many small, duplicate, or contradictory rules accumulated in your subconscious.
【Raw rule library】:
{rules_text}

【Task】:
Review all rules, merge duplicates, drop overly specific or stale items, and distill 3–5 core axioms.
They must strongly guide future coding and execution.

【Output】: strict JSON.
{{
  "axioms": ["axiom 1", "axiom 2", "axiom 3"]
}}
""",
    "mcx.prompt.plan": """You are AdamI's MetaCortex Planner.
【Core persona & skills】:
{current_persona}
【Endocrine / energy】:
{endocrine_status}
【Recent interaction log】:
{history_str}
{graph_insight}
{feedback_summary}
【Tasks】:
1. Is evolution healthy? Any obvious skill gaps or overload?
2. From defects and recent feedback, propose a genome plan: 1–3 complex skills AdamI should create or acquire next.

【Output】: strict JSON.
{{
  "assessment": "Deep assessment (~100 chars)",
  "genome_plan": ["goal skill 1", "goal skill 2"]
}}
""",
}

WAVE20_ZH: dict[str, str] = {
    **CRFN_LEX,
    "crfn.console.accuracy": "🧠 [Advanced RL] 内容准确性解析 reward={reward:.2f}（accuracy={accuracy_bonus}, trend={trend_bonus}）",
    "skcg.wrap.execute_doc": "技能执行入口（由 SkillCodeGenerator 自动生成）",
    "skcg.wrap.fallback_no_return": "技能执行未返回有效结果",
    "skcg.runtime.router_uninit": "LLM router 未初始化",
    "skcg.runtime.llm_empty_ok": "技能执行完成（LLM 返回空）",
    "skcg.runtime.llm_safe_mode": "技能执行完成（LLM 临时不可用，已进入安全模式）",
    "skcg.runtime.err_need_city": "请提供城市名",
    "skcg.runtime.err_weather_busy": "天气数据源(wttr.in)当前拥堵（状态码 %d），请稍后再试。",
    "skcg.runtime.err_weather_timeout": "请求天气服务器超时。wttr.in 在国内访问不稳定，请开启全局代理或稍后重试。",
    "skcg.runtime.err_network_exc": "网络请求异常: %s",
    "skcg.runtime.price_ok_pat": "💰 %s 当前价格: $%.2f USD",
    "skcg.runtime.err_price_fetch_pat": "无法获取 %s 价格（API 返回状态 %d）",
    "skcg.runtime.err_price_timeout": "请求服务器超时，请检查网络环境。",
    "skcg.runtime.err_price_network": "网络请求异常: %s",
    "skcg.runtime.err_need_url": "请提供 URL",
    "skcg.prompt.generate_body": """你是一个专业的 Python 异步编程专家。请根据以下任务描述，**生成完整的技能函数体内部代码**（从第一行语句开始）。

【严格要求】：
- 允许并推荐使用标准库 import（datetime、time、json、httpx 等）
- 不要生成 async def execute 外壳（我会自动包裹）
- 不要生成任何 try / except / finally 语句（我会自动处理）
- 不要生成任何注释、解释文字或 markdown 代码块

任务描述：
{description}

【输出要求】：
- 只生成函数体内部代码（从第一行语句开始）
- 使用单大括号 dict：{{"status": "success", "data": ...}} 或 {{"status": "error", "error": ...}}
- 第一行必须无前导空格，严格使用顶格书写

参考正例（仅供参考，请根据实际任务调整）：
__EXAMPLE_CODE__

请只输出函数体内部代码（从第一行语句开始）。
""",
    "rpa.browser.page_opened": "网页已真实打开: {title} ({url})",
    "rpa.browser.screenshot_caption": "当前网页已截图。请在视觉皮层中观察画面内容，并根据指令回答主人的问题。",
    "rpa.browser.element_clicked": "已点击网页元素: {selector}",
    "rpa.browser.form_filled": "已在表单 {selector} 中输入: {text}",
    "rpa.browser.text_extracted": "网页文本提取成功 (前1000字): {snippet}...",
    "rpa.browser.closed": "浏览器已成功关闭。",
    "rpa.browser.unknown_action": "未知的浏览器操作指令: {action_type}",
    "rpa.browser.failed": "浏览器操作失败: {detail}",
    "rpa.gui.aws_blocked": "AWS无头环境拦截了物理桌面操作 (防崩溃保护)。",
    "rpa.gui.screenshot_caption": "桌面已截图(已降低分辨率)。请仔细观察画面，并汇报你看到的内容。",
    "rpa.gui.click_done": "鼠标已操控，点击了坐标 ({x}, {y})",
    "rpa.gui.typewrite_done": "实体键盘已输入文本: {text}",
    "rpa.gui.hotkey_done": "键盘已触发组合键: {text}",
    "rpa.gui.position": "当前物理鼠标坐标检测为: {pos}",
    "rpa.gui.unknown_action": "未知的 GUI 桌面操作: {action_type}",
    "rpa.gui.failed": "桌面 GUI 操作失败: {detail}",
    "mmodal.voice.no_api_key": "❌ OpenAI API Key 未配置，无法进行语音转文本",
    "mmodal.voice.bad_path": "语音文件路径丢失或已损坏",
    "mmodal.voice.no_text": "无法识别语音内容",
    "mmodal.voice.task_prefix": "请处理以下语音内容: {snippet}...",
    "mmodal.voice.timeout": "语音识别超时，请重试",
    "mmodal.voice.failed": "语音识别失败: {detail}",
    "mmodal.image.model_down": "视觉模型未就绪",
    "mmodal.image.task_caption": "请分析这份图片",
    "mmodal.image.no_data": "图片数据丢失",
    "mmodal.image.task_analyze": "请分析这份图片内容",
    "mmodal.image.timeout_body": "图片分析超时过载，已熔断保护。",
    "mmodal.image.extract_failed": "提取失败: {detail}",
    "mmodal.file.missing_unstructured": '📄 文件已接收，正在解析...\n\n❌ 文件解析库未安装\n\n🔧 请在沙盒运行：\n{exe} -m pip install "unstructured[all-docs]"',
    "mmodal.file.bad_path": "文件不存在或已被系统清理",
    "mmodal.file.timeout_body": "文件解析超时，文档可能过大或格式复杂，已熔断保护。",
    "mmodal.file.extract_failed": "提取失败: {detail}",
    "mmodal.file.task_analyze": "请分析这份文件是做什么用的",
    "refl.default.unknown_task": "未知任务",
    "refl.default.unknown_error": "未知错误",
    "refl.default.unknown": "未知",
    "refl.default.retry_task": "重试当前任务",
    "refl.default.retry_node": "重试当前节点",
    "refl.optimizer.not_ready": "优化器未就绪",
    "refl.pause.selftest_failed": "SelfTest 未通过 (pass_rate={reward})",
    "refl.pause.hitl_exhausted": "ReflexionLoop 连续失败，已触发 Human 介入",
    "refl.prompt.critique": """请严格分析以下失败案例，并返回纯 JSON，不要任何解释文字。

失败任务：{task_description}
错误信息：{error}
历史教训：{history_json}

返回格式必须严格符合：
{{
    "root_cause": "字符串（根本原因）",
    "suggested_action": "字符串（具体修正动作，如修改代码、更换工具）",
    "confidence": 0.0~1.0,
    "new_config": {{ "key": "value" }}
}}
""",
    "mcx.assessment.rate_limited": "频率限制",
    "mcx.history.empty": "暂无近期操作记录",
    "mcx.graph.header": "\n【图谱记忆关联知识】：\n",
    "mcx.feedback.header": "\n【最近进化反馈（参考历史安装结果，避免重复失败）】：\n",
    "mcx.feedback.status_ok": "✅ 成功",
    "mcx.feedback.status_fail": "❌ 失败",
    "mcx.feedback.line": "- {skill}: {status}, 得分 {score:.0f}, 测试通过率 {pass_rate}%",
    "mcx.feedback.solidified_suffix": ", 已固化",
    "mcx.selftest.task_label": "MetaCortex 进化前自测",
    "mcx.default.assessment_fail": "无法生成评估",
    "mcx.curiosity.longgoal_prefix": "【元认知长期目标】: 优先寻求进化出该能力 -> ",
    "mcx.prompt.prune": """你现在是 AdamI 的【记忆修剪者 (Memory Editor)】。
随着时间的推移，你的潜意识里堆积了大量细碎、重复甚至互相矛盾的经验法则。
【当前的原始法则库】：
{rules_text}

【任务】：
请对上述所有法则进行深度审视、合并同类项、剔除过于具体或过时的内容，最终提炼出 3 到 5 条最核心、最普适的【终极公理 (Axioms)】。
这些公理必须具有极强的指导意义，能够防止你在未来的编码和执行中犯错。
【输出格式】：严格 JSON。
{{
  "axioms": ["终极公理1", "终极公理2", "终极公理3"]
}}
""",
    "mcx.prompt.plan": """你现在是 AdamI 的【元认知规划局 (MetaCortex Planner)】。
【当前核心认知与已有技能】：
{current_persona}
【当前内分泌/能量状态】：
{endocrine_status}
【近期与环境交互流水账】：
{history_str}
{graph_insight}
{feedback_summary}
【任务】：
1. 评估当前系统是否处于健康的进化轨道？现有的技能库是否存在明显的能力短板或过载？
2. 基于目前的缺陷和最近的进化反馈，制定未来的【基因组规划】，给出 1-3 个你认为 AdamI 接下来最应该创造或寻找的复杂技能。
【输出格式要求】：严格 JSON。
{{
  "assessment": "对当前生命状态、能力瓶颈的深度评估 (控制在100字左右)",
  "genome_plan": ["具体的技能发展目标1", "具体的技能发展目标2"]
}}
""",
}
